import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useAppSelector } from "@/lib/appstate";
import { AuthSelector } from "@/lib/appstate/features/auth/selectors";
import { useRouter } from "next/router";
import { UserType } from "@/lib/models/auth";
import { useEffect } from "react";
import CustvomButton from "@/components/common/customButton";
import Header from "@/components/home/Header";
import Hero from "@/components/home/Hero";
import Feature from "@/components/home/Feature";
import Footer from "@/components/home/Footer";

export default function Home() {
  const { isAuthenticated, user } = useAppSelector(AuthSelector);
  const router = useRouter();

  useEffect(() => {
    isAuthenticated && user?.Role === UserType.Anonymous && router.push("/");
    isAuthenticated &&
      user?.Role === UserType.Admin &&
      router.push("/p_admin/admin_page");
    isAuthenticated &&
      user?.Role === UserType.Buyer &&
      router.push("/p_buyer/buyer_page");
    isAuthenticated &&
      user?.Role === UserType.Seller &&
      router.push("/p_seller/seller_page");
  }, [isAuthenticated]);

  return (
    <>
      <Head>
        <title>Land Registry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Hero />
        <Feature />
        <Footer />
      </main>
    </>
  );
}
