export enum ActionType {
  REGISTERED_COMPLETED = "auth/REGISTERED_COMPLETED",
  SIGN_IN_WITH_EMAIL_AND_PASSWORD = "auth/SIGN_IN_WITH_EMAIL_AND_PASSWORD",
  SIGN_IN_WITH_PRIVATE_KEY = "auth/SIGN_IN_WITH_PRIVATE_KEY ",
  AUTH_SUCCESS = "auth/AUTH_SUCCESS",
  AUTH_LOADING = "auth/AUTH_LOADING",
  AUTH_ERROR = "auth/AUTH_ERROR",
  AUTH_CLEAR_ERROR = "auth/AUTH_CLEAR_ERROR",
  LOGOUT = "auth/LOGOUT",
  INITIAL_LOAD = "auth/INITIAL_LOAD",
}
